# syntax=docker/dockerfile:1
name: Docker Hub Image Deploy
on:
  push:
    branches: ["main", "develop"]
  # Optional: Add workflow dispatch to manually trigger
  workflow_dispatch:

jobs:
  docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Extract SERVER_VERSION from launch.sh
        id: extract-version
        run: |
          # More robust version extraction
          SERVER_VERSION=$(grep -E '^SERVER_VERSION=' launch.sh | cut -d '=' -f2 | tr -d '"')
          echo "Extracted version: $SERVER_VERSION"
          echo "SERVER_VERSION=$SERVER_VERSION" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push the Docker image (versioned tag)
        uses: docker/build-push-action@v5.3.0
        with:
           context: .
           push: true
           platforms: linux/amd64,linux/arm64  # Multi-arch support
           tags: ${{ secrets.DOCKERHUB_USERNAME }}/allthemods10:${{ env.SERVER_VERSION }}
           cache-from: type=gha
           cache-to: type=gha,mode=max

      - name: Build and push the Docker image (latest tag)
        if: ${{ github.ref_name == 'main' }}
        uses: docker/build-push-action@v5.3.0
        with:
           context: .
           push: true
           platforms: linux/amd64,linux/arm64  # Multi-arch support
           tags: ${{ secrets.DOCKERHUB_USERNAME }}/allthemods10:latest
           cache-from: type=gha
           cache-to: type=gha,mode=max

      # Optional: Slack or Discord notification step
      # - name: Notify deployment
      #   uses: 8398a7/action-slack@v3
      #   with:
      #     status: ${{ job.status }}
      #     fields: repo,message,commit,author,action,eventName,ref,workflow
